
exclude:
  languages

mapping:
  "David Molineus <david.molineus@netzmacht.de>":
    - "David Molineus <mail@netzmacht.de>"
  "Ingolf Steinhardt <info@e-spin.de>":
    - "xantippe <info@e-spin.de>"
    - "zonky2 <info@e-spin.de>"